#!/bin/sh

set -e
set -x

if [ -z $ANDROID_HOME ]; then
    if [ -e ~/.android/bashrc ]; then
        . ~/.android/bashrc
    else
        echo "ANDROID_HOME must be set!"
        exit
    fi
fi

projectroot=`pwd`
# standardize timezone to reduce build differences
export TZ=UTC
TIMESTAMP=`git log -n1 --format=format:%ai`

git reset --hard
git clean -fdx
git submodule foreach --recursive git reset --hard
git submodule foreach --recursive git clean -fdx
git submodule sync --recursive
git submodule foreach --recursive git submodule sync
git submodule update --init --recursive

android update lib-project --path .

if [ -e ~/.android/ant.properties ]; then
    cp ~/.android/ant.properties $projectroot/
else
    echo "skipping release ant.properties"
fi

faketime -f "$TIMESTAMP" make -C external/
faketime -f "$TIMESTAMP" ndk-build
faketime "$TIMESTAMP" ant release

# `ant release` handles the gpg signing
